ALTER TABLE `post` ADD COLUMN `created_at` TIMESTAMP NOT NULL
    DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `post` ADD COLUMN `updated_at` TIMESTAMP NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;
