CREATE TABLE IF NOT EXISTS `policy`(
    `id` INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `comment` VARCHAR(255) NOT NULL,
    `start` TIMESTAMP,
    `end` TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
